default_install_hook_types: [ pre-commit, pre-push ]

repos:
- repo: local
  hooks:
    - id: make-format
      name: Run formatting
      entry: make
      args: [ format ]
      language: system
      pass_filenames: false

    - id: make-lint
      name: Run linting
      entry: make
      args: [ lint ]
      language: system
      pass_filenames: false

    - id: build-docs
      name: Build documentation
      entry: make
      args: [ build-docs ]
      language: system
      pass_filenames: false
      stages: [ pre-push ]
