site_name: Cycleformers
site_url: https://wrmthorne.github.io/cycleformers
repo_name: wrmthorne/cycleformers
repo_url: https://github.com/wrmthorne/cycleformers

theme:
  name: material
  
plugins:
  - mkdocstrings

nav:
  - Get Started:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
  - Reference:
    - CycleTrainer: reference/cycle_trainer.md
    - MACCT: reference/macct.md