model:
  model_name_or_path: google/flan-t5-small

generation:
  max_length: 128
  do_sample: true
  top_k: 0
  top_p: 0.9
  temperature: 0.7

# TODO How to deal with trainer args potentially appearing twice
trainer:
  log_every_n_steps: 100
  num_train_epochs: 1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8