python ../../train.py \
    --model_name_or_path t5-small \
    --task seq2seq_lm \
    --data_a conll2003/A \
    --data_b conll2003/B \
    --output_dir models/CycleNER \
    --use_wandb \
    --wandb_project cycle-lightning-ner \
    --wandb_run_name CycleNER \
    --train_batch_size 16 \
    --lr_a 3e-4 \
    --lr_b 3e-4 \