name: flash_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - ninja
  - gcc=12.3.0
  - gxx=12.3.0
  - pip
  - pip:
      - flash-attn==2.7.0.post2
      - wandb
