name: Build Documentation

on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        description: "If true, the docs will be deployed."
        default: false  

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: 3.11
      
      - name: Build & maybe deploy documentation
        run: |
          poetry run mkdocs build --verbose --clean
          if ${{ inputs.deploy }}; then
            poetry run mkdocs gh-deploy --force
          fi
