name: Build Documentation

on:
  workflow_call:
  workflow_dispatch:
  

jobs:
  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      
      - name: Install dependencies
        run: |
          poetry env list
          poetry env use $(which python3)
          poetry env list
          poetry install
      
      - name: Run doctests
        run: poetry run python -m doctest **/*.py

  build-docs:
    needs: doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      
      - name: Install dependencies
        run: poetry install --only docs
        shell: bash
      
      - name: Build & deploy documentation
        run: |
          poetry run mkdocs build --verbose --clean
          poetry run mkdocs gh-deploy --force