name: Code quality checks & tests
on:
  workflow_call:

permissions:
  contents: write

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      # Cheapest check first
      - name: Run audit
        run: make audit

      - name: Run quality checks
        run: make quality

      - name: Run doctests
        run: poetry run python -m doctest **/*.py

      - name: Run tests with coverage
        run: >
          poetry run pytest
          --cov=src/cycleformers
          --cov-report=xml
          --cov-report=term-missing tests/
          tests/
          --all
          --instafail
          -n auto
          --junitxml=junit.xml
          # --cov-fail-under=80
      
      - name: Generate coverage badge
        run: |
          mkdir -p .github/badges
          poetry run genbadge coverage -i coverage.xml -o .github/badges/coverage.svg
          poetry run genbadge tests -i junit.xml -o .github/badges/build.svg
      
      - name: Commit badge
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Fetch and checkout the PR branch
          git fetch origin ${{ github.head_ref }}
          git checkout -f ${{ github.head_ref }}
          git add .github/badges/coverage.svg .github/badges/build.svg
          git commit -m "Update build and coverage badges" || exit 0
          git push origin ${{ github.head_ref }}
