name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  checks:
    uses: ./.github/workflows/checks.yml

  build-docs:
    uses: ./.github/workflows/build-docs.yml