name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  checks:
    uses: ./.github/workflows/checks.yml

  build-docs:
    uses: ./.github/workflows/build-docs.yml

  add-badge:
    needs: [checks, build-docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-poetry
        with:
          python-version: 3.11
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate build badge
        run: |
          mkdir -p .github/badges
          # If we got to this step, build succeeded
          poetry run genbadge build -n "build" -s "passing" -c "green" -o .github/badges/build.svg

      - name: Commit badges
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/coverage.svg .github/badges/build.svg
          git commit -m "Update badges" || exit 0
          git push