name: Publish to PyPi

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/cycleformers
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: ./.github/actions/setup-poetry
      with:
        python-version: 3.11

    - name: Run quality checks
      uses: ./.github/workflows/checks.yml

    - name: Python Semantic Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        pip install python-semantic-release
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release version
        semantic-release publish

  documentation:
    name: Build & deploy documentation
    uses: ./.github/workflows/build-docs.yml
    with:
      deploy: true
